# Google credentials and configuration
google_client_id:      600142248567-mhjca82osqlvvg3q02kje76u5nj4kj45.apps.googleusercontent.com

google_client_secret:  fceDlnDDPrDm2VX6b6Puarnc

google_project_id:     carbonphp-191421

# options are "mysql", "postgres", "mongodb", or "datastore" -
# This is the only variable on this page that may stay the same
bookshelf_backend: mysql  # C6 requires INNODB ( leave this if unsure )

# configure CloudSQL for MySQL or PostgreSQL backend
cloudsql_connection_name: carbonphp-191421:us-central1:carbonphpmaster

cloudsql_database_name: CarbonPHP

cloudsql_user: root               # probably should avoid this as well

cloudsql_password: Huskies!99         # I do not recommend using my black labs name as a password

cloudsql_port: 3306

# configure Mongo backend
# mongo_url: YOUR_MONGODB_URL
# mongo_database: YOUR_MONGO_DATABASE
# mongo_collection: YOUR_MONGO_COLLECTION
