# Google credentials and configuration
google_client_id:      this is from the oauth credentials page

google_client_secret:

google_project_id:     your project id, this should be the first section of the connection name

# options are "mysql", "postgres", "mongodb", or "datastore" -
# This is the only variable on this page that may stay the same
bookshelf_backend: mysql  # C6 requires INNODB ( leave this if unsure )

# configure CloudSQL for MySQL or PostgreSQL backend
cloudsql_connection_name: instance id here

cloudsql_database_name:

cloudsql_user: root               # probably should avoid this as well

cloudsql_password: Huskies!99         # I do not recommend using my black labs name as a password

cloudsql_port: 3306

# configure Mongo backend
# mongo_url: YOUR_MONGODB_URL
# mongo_database: YOUR_MONGO_DATABASE
# mongo_collection: YOUR_MONGO_COLLECTION
